Project=Asenso Mobile V3 Application
Device\ Brand\ &\ Model=Honor CRT-NX1
Android\ Version=15
Environment=Dev
Node\ Version=v22.14.0
OS\ Platform,\ Release,\ &\ Version=win32, 10.0.19045, Windows 10 Pro